---
- name: Synchronize module
  hosts: ata_demo 

  tasks:
    - name: Synchronize files
      ansible.builtin.synchronize:
        src: sync_files 
        dest: /tmp/sync_files
        rsync_path: /usr/bin/rsync
